### ISSUE TITLE
Xcode error

### ISSUE THREAD

**Issue by jay-b** [Anyline/anyline-ocr-cordova-module#1]
Trying to test this and cannot build in Xcode with the following error: 

Lexical or Preprocessor issue
'Anyline/Anyline.h file not found
AnylineBaseScanViewController.h

**Comment by JonasLaux** [comment]
Hey,

can you please try reinstall the plugin?
Just execute these in the root directory:
`cordova` plugin remove io-anyline-cordova

`cordova` plugin add io-anyline-cordova

**Comment by jay-b** [comment]
Hey Jonas,

Thanks, I wrestled with it for a few hours last night and got it working in an Ionic app in the end. Works extremely well! Will be certainly be looking at licensing this going forward. 

Cheers.

**Comment by JonasLaux** [comment]
Glad to hear! 
Thanks for the support!
