### ISSUE TITLE
Crash on iOS 9

### ISSUE THREAD

**Issue by Coolcat13** [Anyline/anyline-ocr-cordova-module#10]
We are currently evaluating the anyline SDK with a cordova app on a trial license. Got it to work on iOS 10 and 11, but the only iOS 9 device we have (iPad 2) - the app crashes when starting the scan. No error message, just crashes, it doesn't get to the camera permission prompt, and it looks like that may be where the issue is.

I don't have any more data to give you right now, just wondering if you have seen this issue or maybe if you could test it on your side too.

Thanks in advance

**Comment by JonasLaux** [comment]
Hi,
yes we do support iOS 8 and greater, but we don't support iOS devices with a smaller resolution than 1080p for the camera. 
The iPad 2 has 720p, which is too low.

**Comment by Coolcat13** [comment]
@JonasLaux thanks for that - at least I know what's going on. Is there a better way to handle this than let the scanner crash?

**Comment by Coolcat13** [comment]
@JonasLaux sorry - after checking, it turns out we have an iPad 3 (not 2) which does have a retina display and a 1080p camera - any idea what could be going on? It's running iOS 9.3.5 - the latest for that device. Thanks
