### ISSUE TITLE
Unable to build for ios

### ISSUE THREAD

**Issue by Coolcat13** [Anyline/anyline-ocr-cordova-module#12]
As part of troubleshooting issue #10 (anyline scanner crashing on iOS 9.3.5 on iPad 3 - retina) - we are trying to build for iOS emulator 9.3 using cordova run --emulator, but we are getting a build error related to the i386 platform which is required for emulator - looks like they are not included in the aniline plugin?

ld: warning: ignoring file XXXXX/Plugins/io-anyline-cordova/Anyline.framework/Anyline, missing required architecture i386 in file XXXXX/Plugins/io-anyline-cordova/Anyline.framework/Anyline (3 slices)
Undefined symbols for architecture i386:
  "_OBJC_CLASS_$_AnylineDocumentModuleView", referenced from:
      objc-class-ref in AnylineDocumentScanViewController.o
  "_kCodeTypeUPCE", referenced from:
      ___64-[AnylineEnergyScanViewController barcodeFormatForNativeString:]_block_invoke in AnylineEnergyScanViewController.o
  "_kCodeTypeITF", referenced from:
      ___64-[AnylineEnergyScanViewController barcodeFormatForNativeString:]_block_invoke in AnylineEnergyScanViewController.o
  "_kCodeTypeDataMatrix", referenced from:
      ___64-[AnylineEnergyScanViewController barcodeFormatForNativeString:]_block_invoke in AnylineEnergyScanViewController.o
  "_kCodeTypeEAN13", referenced from:
      ___64-[AnylineEnergyScanViewController barcodeFormatForNativeString:]_block_invoke in AnylineEnergyScanViewController.o
  "_OBJC_CLASS_$_AnylineOCRModuleView", referenced from:
      objc-class-ref in AnylineOCRScanViewController.o
  "_kCodeTypeCode128", referenced from:
      ___64-[AnylineEnergyScanViewController barcodeFormatForNativeString:]_block_invoke in AnylineEnergyScanViewController.o
  "_kCodeTypeCode93", referenced from:
      ___64-[AnylineEnergyScanViewController barcodeFormatForNativeString:]_block_invoke in AnylineEnergyScanViewController.o
  "_kCodeTypePDF417", referenced from:
      ___64-[AnylineEnergyScanViewController barcodeFormatForNativeString:]_block_invoke in AnylineEnergyScanViewController.o
  "_kCodeTypeCode39", referenced from:
      ___64-[AnylineEnergyScanViewController barcodeFormatForNativeString:]_block_invoke in AnylineEnergyScanViewController.o
  "_kCodeTypeQR", referenced from:
      ___64-[AnylineEnergyScanViewController barcodeFormatForNativeString:]_block_invoke in AnylineEnergyScanViewController.o
  "_OBJC_CLASS_$_AnylineMRZModuleView", referenced from:
      objc-class-ref in AnylineMRZScanViewController.o
  "_kCodeTypeAztec", referenced from:
      ___64-[AnylineEnergyScanViewController barcodeFormatForNativeString:]_block_invoke in AnylineEnergyScanViewController.o
  "_OBJC_CLASS_$_AnylineEnergyModuleView", referenced from:
      objc-class-ref in AnylineEnergyScanViewController.o
  "_kCodeTypeEAN8", referenced from:
      ___64-[AnylineEnergyScanViewController barcodeFormatForNativeString:]_block_invoke in AnylineEnergyScanViewController.o
  "_OBJC_CLASS_$_AnylineLicensePlateModuleView", referenced from:
      objc-class-ref in AnylineLicensePlateViewController.o
  "_OBJC_CLASS_$_ALUIConfiguration", referenced from:
      objc-class-ref in AnylineSDKPlugin.o
  "_OBJC_CLASS_$_ALOCRConfig", referenced from:
      objc-class-ref in AnylineOCRScanViewController.o
  "_OBJC_CLASS_$_AnylineBarcodeModuleView", referenced from:
      objc-class-ref in AnylineBarcodeScanViewController.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by JonasLaux** [comment]
Hi @Coolcat13 ,
i'm sorry, but we don't support i386 anymore. Our SDK is only build for armv7, x86_64 and arm64.
But it's not yet reflected in our Documentation, we will change that!
Thanks
