### ISSUE TITLE
BarcodeFormat specification

### ISSUE THREAD

**Issue by Coolcat13** [Anyline/anyline-ocr-cordova-module#15]
How can we limit barcode format in cordova config as per this documentation: https://documentation.anyline.com/toc/modules/barcode/index.html

Thanks

**Comment by JonasLaux** [comment]
Unfortunately, this config is not available on the cordova part. You can set them in the native parts.
 
Right now, we have a lot going on, so i can't promise any date, when we can implement this to the Cordova plugin. But it's just pipe a variable from the native part through the Cordova configuration. Always feel free to create a pull request for it.
