### ISSUE TITLE
not working on IOS for ionic cordova

### ISSUE THREAD

**Issue by iaskari** [Anyline/anyline-ocr-cordova-module#17]
I created an app using cordova SDK it's working perfectly with Android but when I tried to build it for IOS I got an error "data parameter nil".

the app using ionic

**Comment by JonasLaux** [comment]
hi,
could you please provide some more informations? How do you build the app (Cordova CLI?, xcode?). How did you implement our plugin? Also, can you post the whole crashlog?

**Comment by iaskari** [comment]
Hi,
I build the app using both Cordova CLI and xcode ,
I install the plusgin using `ionic cordova plugin add io-anyline-cordova` ,
I created a ionic provider and call the cordova plugin 
`  (<any>window).cordova.exec(this.onResult, this.onError, "AnylineSDK", scanmode, [licenseKey,{
        "captureResolution": "1080",
  
        "cutout": {
          "style": "rect",
          "maxWidthPercent": "90%",
          "maxHeightPercent": "90%",
          "alignment": "top_half",
          "strokeWidth": 2,
          "cornerRadius": 4,
          "strokeColor": "FFFFFF",
          "outerColor": "000000",
          "outerAlpha": 0.3,
          "cropPadding": {
            "x": -30,
            "y": -90
          },
          "cropOffset": {
            "x": 0,
            "y": 90
          }
        },
        "flash": {
          "mode": "manual",
          "alignment": "bottom_right"
        },
        "beepOnResult": true,
        "vibrateOnResult": true,
        "blinkAnimationOnResult": true,
        "cancelOnResult": true,
        "visualFeedback": {
          "style": "rect",
          "strokeColor": "0099FF",
          "strokeWidth": 2
        }
      }
        ]);`

this code is working for the android but in the Iphone I got the same error 

` *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'data parameter is nil'
*** First throw call stack:
(0x18542e364 0x184674528 0x18542e2ac 0x185d91f34 0x1009366dc 0x10093654c 0x10092a9c4 0x100960204 0x10092a830 0x100935410 0x100934ef0 0x10133abec 0x1020c92cc 0x1020c928c 0x1020cdea0 0x1853d6544 0x1853d4120 0x1852f3e58 0x1871a0f84 0x18e97367c 0x101308a38 0x184e1056c)
libc++abi.dylib: terminating with uncaught exception of type NSException` 

the error is on this line ` [mrzModuleView setupWithLicenseKey:self.key delegate:self error:&error];`

**Comment by JonasLaux** [comment]
Sounds like you're resource bundle isn't loaded probably. 
Did Cocoapods download the Anyline bundle while you added the plugin? 
Can you please try to go to your platforms/ios folder and run 
`pod update`

**Comment by iaskari** [comment]
you're right,Thanks
