### ISSUE TITLE
Ionic3 Cordova build - Anyline.h missing

### ISSUE THREAD

**Issue by isharko** [Anyline/anyline-ocr-cordova-module#18]
Having issues building the app, as it throws the error that Anyline.h is missing. 
Error: 'Anyline.h' file not found with <angled> include; use "quotes" instead
Specs:

Node version: v7.6.0
Cordova version: 8.0.0
<plugin name="io-anyline-cordova" spec="^3.21.0" />
Xcode 9.2

Please advise on a resolution

**Comment by JonasLaux** [comment]
Hi,
this seems like the Anyline iOS SDK isn't loaded correctly. Do you have cocoapods installed and did you install the AnylinePlugin with 
`cordova/ionic add io-anyline-cordova` ?
Do you see, in the Log, that the AnylinePod is loaded?
Also, you could go into your platform/iOS and run `pod update`?

**Comment by JonasLaux** [comment]
I will close this for now. If you have still problems, feel free to reopen this issue.
