### ISSUE TITLE
Google Play Services old version dependency

### ISSUE THREAD

**Issue by Coolcat13** [Anyline/anyline-ocr-cordova-module#19]
Anyline plugin has a dependency on Google Play Vision Services v 8.4.0 in gradle file which is very old. Other plugins we use have a requirement for a more recent version. Why is 8.4.0 required with Anyline SDK?

**Anyline Cordova Plugin version:** 
3.20.1

**I'm submitting a ...**  
[ ] bug report
[ ] feature request
[X] general question

**Occurring on ...**  
[X] Android
[ ] iOS

**Current behavior:**
Anyline plugin has a dependency on Google Play Vision Services v 8.4.0 in the gradle file (https://github.com/Anyline/anyline-ocr-cordova-module/search?utf8=%E2%9C%93&q=play-services-vision) which is very old. Other plugins we use have a requirement for a more recent version. Why is 8.4.0 required with Anyline SDK?

**Expected behavior:**
Anyline plugin should be using a more recent version of Google Play Services

**Steps to reproduce:**
Build cordova app with Anyline plugin

**Related code:**
https://github.com/Anyline/anyline-ocr-cordova-module/blob/bf762c2976b518407cd586a66bfd38b59210ec63/plugin/src/android/anyline.gradle

-->

**Comment by JonasLaux** [comment]
Hi,
thank you for mentioning! We will update and test the dependencies in our next Release!

**Comment by Coolcat13** [comment]
Hi there - can you confirm if this has been updated in 3.22? Thanks!

**Comment by danielalbertini** [comment]
Hi,

yes this is updated in the 3.22 release

https://github.com/Anyline/anyline-ocr-cordova-module/commit/4aed82a5fff18be59a3d85ab13f93bb904ceadd2#diff-d2965ceb1a27b1fc73b79dbcb5cc422a

Best regards,
Daniel
