### ISSUE TITLE
Plugin Structure

### ISSUE THREAD

**Issue by Giusti** [Anyline/anyline-ocr-cordova-module#2]
Hey,

I am working with Telerik Appbuilder, usually when installing a Plugin I just have to import the zip into visual studio and everything is working, when I do that with this plugin the configurations of the plugin change the appname and the whole app is not working anymore. I also noticed, that the Plugin  structure is completely different from any other Plugins. Normally there is an www folder with a js file containing the cordova.exec I copied your anyline.barcode.js and used that instead, but still after removing the example and hooks folder the res folder is causing problems. 
Maybe you can clarify what I have to do to import this plugin like the other plugins I installed so far (20+)

Regards Chris

**Comment by danielalbertini** [comment]
Hi Chris,

the easiest way to install the plugin is via npm. Therefore you just have to type `cordova plugin add io-anyline-cordova` in your project folder.

The other possibility is downloading or cloning this repo and then again type `cordova plugin add $path_to_anyline-ocr-cordova-module` in your project folder.

Best Regards,
Daniel

**Comment by Giusti** [comment]
Sadly I am not working via Cordova cli and dont have access to npm. But as said with every other plugin so far I had no problems using "Import Plugin" in visual Studio (Telerik Appbuilder). But I guess I have to try to modify the plugin structure until it works.

**Comment by danielalbertini** [comment]
Did you get it to work. Keep in mind that the actual Anyline frameworks are downloaded in the plugin via maven/cocoapods. I'm not sure if the import plugin in Visual Studio downloads the dependencies like the cordova cli does. You can download the frameworks at https://anyline.io/download

**Comment by Giusti** [comment]
Sadly I was not able to get it to work, in fact it made things worse, it seems that the import corrupted some of my configurations because it took the configs from some files in your plugin and overrode mine. App name permissions and other things changed so I couldnt deploy my app anymore.... I also had conflicts with color.xml because they were detected as duplicate. The only choice I had was to revert all changes back to before I added the plugin. I am really not sure whats so different with this plugin. The only possiblities to add plugins is to import from local zip via bower or via telerik verified plugins and it seems that the structure of the plugin doesnt work.
All of my plugins look like this
[plugin structure](https://www.imageupload.co.uk/image/B3oa)

problem is when I delete the res folder and gradle file in the src/android folder and adapt the plugin xml nothing is working anymore....

Maybe we can get it to work together in the meanwhile I tried ocrad.js / tessaract but Id really love to try Anyline since it seems to work in combination with wikitude which we already use.

**Comment by Giusti** [comment]
Hey have you had a chance to look at what i posted, really would like to use your plugin

**Comment by JonasLaux** [comment]
Hey,

sorry, we didn't have time to restructure the plugin. I will plan some time for it in the next sprint.

**Comment by Giusti** [comment]
Hey I just got an email with a new Anyline release still with the old structure any plans on changing that?

**Comment by JonasLaux** [comment]
Hey, 
thanks for staying tuned. We are planning to fit the requirements of the plugin structure to help you out. Unfortunately we have a lot going on and only limited resources. I would say that this improvement will be implemented in 2 or 3 months without guarantee.
Sorry for the circumstances. But at any time feel free to send us an pull-request with your approach.

**Comment by EvanWieland** [comment]
@Giusti, did you finalize a solution for this problem? I am using Telerik as well and am having issues.

**Comment by Giusti** [comment]
@EvanWieland Well i tried changing the plugin structure to get it working but sadly it never worked out couldnt get a successful build working.

**Comment by EvanWieland** [comment]
@Giusti That's no good. I can get an .apk to build just fine, but can't get an .ipa to build.

**Comment by Giusti** [comment]
But instead I went with tesseract.js which is doing okayish id say give it a try if u want

**Comment by EvanWieland** [comment]
Interesting, so your just wanting to do general OCR. I'm attempting to do document scanning, so it doesn't look like tesseract will work out for that. Thanks tho!

**Comment by Giusti** [comment]
@EvanWieland ye i guess tesseract wont work out in your case could you maybe share what you changed to get an apk working? So i can give it another try?

**Comment by EvanWieland** [comment]
@Giusti I actually didn't change any thing. Perhaps the latest AppBuilder version changed something? I added the plugin using ` appbuilder plugin add anyline`.

**Comment by EvanWieland** [comment]
@Giusti I also got iOS working on with Telerik too. [https://github.com/Anyline/anyline-ocr-cordova-module/issues/7](https://github.com/Anyline/anyline-ocr-cordova-module/issues/7)

**Comment by Giusti** [comment]
@EvanWieland ohh well I gotta try again maybe telerik changed things to get it working thank you very much for the tip

**Comment by EvanWieland** [comment]
@Giusti I can walk you through it if you have any issues.
