### ISSUE TITLE
exec proxy not found for

### ISSUE THREAD

**Issue by 8178520204** [Anyline/anyline-ocr-cordova-module#20]
I am trying to configure anyline with an cordova progect , I integrated licence key as well and i took code from GitHub"https://github.com/Anyline/anyline-ocr-cordova-module"
but its showing error "Error: exec proxy not found for :: AnylineSDK :: AUTO_ANALOG_DIGITAL_METER"
 can any one help mine..

![reeor](https://user-images.githubusercontent.com/36916196/38717591-7142b2f2-3f05-11e8-9ab3-d71f7f04e63d.PNG)

my code is here...
https://drive.google.com/file/d/11CHnyVbAxXrI6TKsb2EEB5YCkd_DJ-Cn/view?usp=sharing

**Comment by JonasLaux** [comment]
HI,

can you please add the additional information of the issue template, so we have enough informations to help you?

How did you install the Plugin?

Which Platform are you testing?

Did you every installation step described in the ReadMe?

**Comment by 8178520204** [comment]
​
 ocr.rar
<https://drive.google.com/file/d/11CHnyVbAxXrI6TKsb2EEB5YCkd_DJ-Cn/view?usp=drive_web>
​i have attached my complete code plz review, there you will get that error
..

**Comment by 8178520204** [comment]
https://drive.google.com/file/d/11CHnyVbAxXrI6TKsb2EEB5YCkd_DJ-Cn/view?usp=sharing

**Comment by 8178520204** [comment]
and my requirement is only one module meter reader (Analog and digital )

**Comment by JonasLaux** [comment]
Hey,

i downloaded your app and could not reproduce it. I managed to it to launch.

![image](https://user-images.githubusercontent.com/24549865/38736159-764b06a2-3f2b-11e8-98df-fde1f982a8d0.png)


Also, i would suggest, because there is no code written jet in your www directory, to first try it out with only Anyline as Plugin, and add the other plugins afterwards.
Also, your "proxy" Error doesn't seem to be related to Anyline

**Comment by 8178520204** [comment]
can you plz send me code in zip file, for proper understanding..

**Comment by 8178520204** [comment]
Can you please send me code in zip file, for proper understanding..

**Comment by JonasLaux** [comment]
I didn't change anything.

**Comment by 8178520204** [comment]
Hi ,
 i am trying to configure it but not succeed can you please send me code in
zip , for my proper understanding.



Rohit Shukla
Firmwisegroup pvt ltd
Jaipur Rajasthan 302005

**Comment by 8178520204** [comment]
I want to integrate Anyline in an existing application for Demo.

so please send me code ASAP.

**Comment by marcelmerkx** [comment]
<8178520204 > -you are mostly replying to yourself.

It looks like you already correctly included Anyline into your project. You just need to find help to build the cordova project. E.g. can you build a Cordova sample app ? can you build an app without Anyline? 
Per above, JonasLaux was able to build and launch your project.

**Comment by 8178520204** [comment]
yes I am able to build project without anyline

**Comment by JonasLaux** [comment]
Hi,
as i said, i did not change anything in your Code. I just run the Project on Android. As i said, i don't think that your Problems doesn't correlate with Anyline.

Also, your Code is just our Example App. I think you can build your app, because it doesn't use any of the other plugins.
