### ISSUE TITLE
Technical supports

### ISSUE THREAD

**Issue by 8178520204** [Anyline/anyline-ocr-cordova-module#21]
can you please upload a video. how to integrate anyline with cordova project ,
I searched on youtube , now your supprted videos are available only for android.

Now i am trying to integrate anyline with an existing cordova project , but i dont know where I am doing wrong step. please upload a video and if possible then upload complete code in zip

**Comment by JonasLaux** [comment]
Hello,
sorry for the late response, but unfortunately, we don't have time to produce a video for integrating Anyline with Cordova. I hope you can manage it the Documentation.

**Comment by 8178520204** [comment]
Yeah, I did it
