### ISSUE TITLE
Plugin repo install has timed out

### ISSUE THREAD

**Issue by speralta117** [Anyline/anyline-ocr-cordova-module#23]
**Anyline Cordova Plugin version:** 
3.27.1

**I'm submitting a ...** 
[ X] bug report
[ ] feature request
[ ] general question

**Occurring on ...**  
[ ] Android
[ X] iOS

**Current behavior:**
I'm trying to include the plugin using Phonegap build and it only works for android, I keep getting this message for iOS 
'Error - Plugin repo install has timed out on the following plugin, please try building again: io-anyline-cordova@~3.27.0'

**Expected behavior:**
Install the plugin through phonegap build

**Steps to reproduce:**
1. Generate Build through Phonegap Build

**Related code:**

```
insert code snippets here
```

**Other information:**
Similar Issue found here: 
https://forums.adobe.com/message/8946680#8946680

![image](https://user-images.githubusercontent.com/33643170/46703173-a0c7c580-cbeb-11e8-8b45-07fa0a25f556.png)

**Comment by JonasLaux** [comment]
Hi,
is there any kind of log instead of the timeout?
Maybe it's because of Cocoapods? do you have properly installed Cocoapods with Phonegap and updated the Pod Repo?

**Comment by speralta117** [comment]
Hi,
It's the only Log that I got.
When I add the plugin locally it takes sometime but it works properly, so I'm guessing the Cocoapods are correctly installed, the problem comes when you try to do this using PhoneGap build https://build.phonegap.com/

I don't have access to the Cocoapods using that service to compile my project.

**Comment by JonasLaux** [comment]
Sorry, for not coming back to you. Unfortunately, we can't provide any more support, unless we get some information about the crash..
