### ISSUE TITLE
Won't compile on PhoneGap Build for iOS CLI

### ISSUE THREAD

**Issue by mendrix** [Anyline/anyline-ocr-cordova-module#26]
**Anyline Cordova Plugin version:** 
ALL greater then 3.15.0, up to and including 5.1.0

**I'm submitting a ...**  
[x] bug report
[ ] feature request
[ ] general question

**Occurring on ...**  
[ ] Android
[x] iOS

**Current behavior:**
version 5.1.0 -->

--------------------------------------------------------------------------------
PLUGIN OUTPUT
--------------------------------------------------------------------------------
Fetching plugin "cordova-plugin-battery-status@1.1.2" via npm
Installing "cordova-plugin-battery-status" at "1.1.2" for ios
Fetching plugin "cordova-plugin-camera@2.3.1" via npm
Installing "cordova-plugin-camera" at "2.3.1" for ios
Fetching plugin "cordova-plugin-compat@^1.1.0" via npm
Installing "cordova-plugin-compat" at "1.2.0" for ios
Fetching plugin "cordova-plugin-file@4.2.0" via npm
Installing "cordova-plugin-file" at "4.2.0" for ios
Plugin dependency "cordova-plugin-compat@1.2.0" already fetched, using that version.
Dependent plugin "cordova-plugin-compat" already installed on ios.
Fetching plugin "cordova-plugin-device@1.1.2" via npm
Installing "cordova-plugin-device" at "1.1.2" for ios
Fetching plugin "cordova-plugin-geolocation@3.0.0" via npm
Installing "cordova-plugin-geolocation" at "3.0.0" for ios
Fetching plugin "cordova-plugin-splashscreen@3.2.2" via npm
Installing "cordova-plugin-splashscreen" at "3.2.2" for ios
Fetching plugin "cordova-plugin-media@2.3.0" via npm
Installing "cordova-plugin-media" at "2.3.0" for ios
Plugin dependency "cordova-plugin-file@4.2.0" already fetched, using that version.
Dependent plugin "cordova-plugin-file" already installed on ios.
Plugin dependency "cordova-plugin-compat@1.2.0" already fetched, using that version.
Dependent plugin "cordova-plugin-compat" already installed on ios.
Fetching plugin "cordova-plugin-network-information@1.2.1" via npm
Installing "cordova-plugin-network-information" at "1.2.1" for ios
Fetching plugin "cordova-plugin-inappbrowser@1.4.0" via npm
Installing "cordova-plugin-inappbrowser" at "1.4.0" for ios
Fetching plugin "cordova-plugin-keyboard@1.1.4" via npm
Installing "cordova-plugin-keyboard" at "1.1.4" for ios
Fetching plugin "cordova-plugin-statusbar@2.4.2" via npm
Installing "cordova-plugin-statusbar" at "2.4.2" for ios
Fetching plugin "cordova-plugin-powermanagement@1.0.5" via npm
Installing "cordova-plugin-powermanagement" at "1.0.5" for ios
"plugman-151 install --platform ios --project /project --plugin io-anyline-cordova@5.1.0 --nohooks=.": Fetching plugin "io-anyline-cordova@5.1.0" via npm
Installing "io-anyline-cordova" at "5.1.0" for ios
Failed to install 'io-anyline-cordova': Error: pod: Command failed with exit code 1
    at ChildProcess.whenDone (/private/project/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Socket.stream.socket.on (internal/child_process.js:381:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close (net.js:611:12)
pod: Command failed with exit code 1

**Expected behavior:**
That it compiles on Adobe PhoneGap Build

**Steps to reproduce:**
<preference name="phonegap-version" value="cli-7.0.1" />

**Comment by JonasLaux** [comment]
https://github.com/OneSignal/OneSignal-Cordova-SDK/issues/186#issuecomment-347623033

**Comment by mendrix** [comment]
That is not possible when using the Adobe PhoneGap Build platform.

**Comment by mendrix** [comment]
Thanks Jonas, 

I will contact the PGB team, see if they can fix it.

https://forums.adobe.com/message/10118352
