### ISSUE TITLE
android-minSdkVersion forced to 19

### ISSUE THREAD

**Issue by mendrix** [Anyline/anyline-ocr-cordova-module#27]
Hi.

When using version 3.27.1 of the io-anyline-cordova plugin,

Our application is forced an android-minSdkVersion of 19,
even when we set it to 24.

We need this to be 24 in some builds, so we can publish multiple apk's to the Google Play store.

Could you please fix this?

We are using PhoneGap Build as our build platform;
Phonegap-version cli-8.1.1
Android Phonegap Version  7.1.2

Yours sincerely

René Vaessen
MendriX

**Comment by JonasLaux** [comment]
Hey,

this could be a leftover from our native SDK, it's in [this line](https://github.com/Anyline/anyline-ocr-cordova-module/blob/master/plugin/src/android/anyline.gradle#L14) or in 3.27.1 it's [this line](https://github.com/Anyline/anyline-ocr-cordova-module/blob/fb93571a53e126a6063cb42887a879b22c8aefd9/plugin/src/android/anyline.gradle#L14).
or it can be a problem with the phonegap build which is described [here](https://stackoverflow.com/questions/27135185/how-can-i-specify-the-minimum-sdk-in-phonegap-it-is-ignoring-android-minsdkvers)

Right now i tried to remove the tag in our plugin and rebuild the whole example app project with the same result, still min version 19 (which was generated by Cordova).
For evaluation purposes, i just created v3.27.1-beta.0 where i removed the minSDK from our plugin. 
Could you try it with that and check back if this solves your issue?
Just call
`cordova plugin add io-anyline-cordova@3.27.1-beta.0`

**Comment by mendrix** [comment]
Hey,

Yes 3.27.1-beta.0 did the trick! 

PS F:\testapk> .\aapt.exe d badging .\MendrixMobilePhoneGap_v2.0.20_Release-noxwalks.apk
package: name='nl.mendrix.mobile' versionCode='697832' versionName='2.0.20'
sdkVersion:'24'
targetSdkVersion:'26'

Great.. can we expect a stable release with this fix?

And.. best wises for the new year..! :)

René Vaessen
MendriX

**Comment by ale-anyline** [comment]
Hi Rene,
Happy new year to you as well :) We'll be delivering the fix in our next release on the 21st of January.

Thank you

**Comment by JonasLaux** [comment]
I released 3.27.2. You can update it now
