### ISSUE TITLE
App size increased after added plugin 

### ISSUE THREAD

**Issue by kaviyarasu1987** [Anyline/anyline-ocr-cordova-module#28]
Our Cordova app size increases up to 122 Mb that makes app slow ,I think it’s because of heavy .aar library size 

Please advise we are using Cordova version 5.4.2

**Comment by JonasLaux** [comment]
So you are using only Android? 
To be clear, this project is not a pure Javascript OCR Module. This is just a wrapper around our native SDK, including the platform specific SDK, our compiled C++ Core and our neural networks.

**Comment by kaviyarasu1987** [comment]
Thanks for your reply

I understand its not any javascript based OCR module and  also if we integrate native .aar file through the direct library or gradle build which increases app size as upto 30%  so it looks like all the library wrapped over in single aar not separated by each scanner functionality , Lets say we need only passport scanner but we should integrate the whole scanning(Passport,QR etc) .aar wrapper library has size more than 50MB which really affects app performance especially hybrid based apps(either create our own plugin using anyline SDK or integrate this existing anyline plugin)

it would be good if we have a separate library(.aar or gradle pugin) for a specific set of scannings  with minimal size(passport.aar/gradle,Qr.arr/gradle etc) I don't think RNN/CNN logics will take much size inside each library, Please let us know if we have any other option available to increase our app performance

**Comment by JonasLaux** [comment]
What can be is, that after the download from NPM, the project on your computer is increased, which is because of the native Windows libraries which are included in our current plugin. But this should not have any impact on your android or iOS project.

**Comment by JonasLaux** [comment]
As there is no further discussion, i will close this issue. Feel free to open it again, if you can provide further informations.
