### ISSUE TITLE
Android 64-bit support

### ISSUE THREAD

**Issue by jp-uq** [Anyline/anyline-ocr-cordova-module#29]
**Anyline Cordova Plugin version:** 
4.1.0

**I'm submitting a ...**  
[ ] bug report
[ ] feature request
[x] general question

**Occurring on ...**  
[x] Android
[ ] iOS

Google announced in their [blog post](https://android-developers.googleblog.com/2019/01/get-your-apps-ready-for-64-bit.html) apps using native code need to support a 64-bit version in addition to the 32-bit version. Have you already planned until you can provide 64-bit versions?

**Comment by JonasLaux** [comment]
Hey,
yes, you're totally right and we are working hard to integrate it in our next Release, which is at the 25.2.
