### ISSUE TITLE
import io.anyline.examples.cordova.R

### ISSUE THREAD

**Issue by maltenorstroem** [Anyline/anyline-ocr-cordova-module#3]
Hi Anyline,

With the newest version 3.8.1.x I get an import error with the package io.anyline.examples.cordova.R. 

error: package R does not exist
            if( System.currentTimeMillis() > lastErrorRecieved + getApplication().getResources().getInteger(R.integer.error_message_delay)) {...}

Is there maybe an issue or do I have to change some settings?
best regards

**Comment by danielalbertini** [comment]
Hi,

did you get experienced some errors while updating? Normally you should not need to change anything on Android. For the iOS plugin we switched to cocoapods to download the sdk.

Best regards,
Daniel
