### ISSUE TITLE
OnError handler not triggered if user denied access to camera

### ISSUE THREAD

**Issue by MaximBelov** [Anyline/anyline-ocr-cordova-module#30]
Hi
I wrapped your examples code to ionic 4 with cordova-ios v5

**Anyline Cordova Plugin version:** 
7.0.1

**I'm submitting a ...** 
[x] bug report
[ ] feature request
[ ] general question

**Occurring on ...**
[ ] Android
[x] iOS 11.3.1, and other versions greater then iOs 10

**Current behavior:**
0. Add breakpoint for "OnError" method
1. Deny access to camera
2. Try Scan with any mode/options
3. "OnError" callback not triggered 

**Expected behavior:**
1. "OnError" callback is triggered

**Video**
https://monosnap.com/file/Gep1u2Xoa9JqLnmzRIiQbLjvevc0p3

**Comment by JonasLaux** [comment]
Do breakpoints trigger anywhere else in the scripts? I'm not quite sure if the debugging is working there.

**Comment by MaximBelov** [comment]
> Do breakpoints trigger anywhere else in the scripts? I'm not quite sure if the debugging is working there.

its working for result and error callback`s
please check my debug video
https://monosnap.com/file/mTAmw2IsmLa88xEiCSE8ekJPVTqUpK

**Comment by MaximBelov** [comment]
fixed in 13.0
https://github.com/Anyline/anyline-ocr-cordova-module/releases/tag/v13.0.0
thnx
