### ISSUE TITLE
INVALID_SENDER with phonegap-plugin-push

### ISSUE THREAD

**Issue by intrasoft-eu** [Anyline/anyline-ocr-cordova-module#32]
I'm trying to add this plugin to my project that uses also phonegap-plugin-push. I had to change FCM version to 17.0.0 to be able to compile project.

I got __INVALID_SENDER__ exception form _phonegap-plugin-push_ when app starts (so I'm not able to init push notifications anymore).

It seems that google-services.json is overwriteen somehow?

**Comment by MaximBelov** [comment]
You can try
https://www.npmjs.com/package/cordova-play-services-version-adapter
