### ISSUE TITLE
not working on android with ionic

### ISSUE THREAD

**Issue by Atee134** [Anyline/anyline-ocr-cordova-module#33]
versions:  
Ionic: 4.1.0
io-anyline-cordova: 10.1.0
Angular: 7.2.2
Android: Both 8.0 and 9.0.1

**I'm submitting a ...**  
[x] bug report
[ ] feature request
[ ] general question

**Occurring on ...**  
[x] Android
[ ] iOS

**Current behavior:**
Very similar to: [https://github.com/Anyline/anyline-ocr-cordova-module/issues/25](url)
I have followed this [https://documentation.anyline.com/toc/platforms/cordova/getting_started.html](url)

and wrote a wrapper service in angular.
My config is basically the same as in the getting started guide.
When I call the scan() method, the cordova.exec gets executed, first time it asks for permission for the camera, then a black screen appears.

`
  private viewConfig =
  {
    camera: {
        captureResolution: '1080'
      },
      flash: {
        mode: 'manual',
        alignment: 'bottom_right'
      },
      viewPlugin: {
        plugin : {
          id : 'OCR_VC',
          ocrPlugin : {
            scanMode : 'AUTO',
            languages : ['www/assets/anyline_capitals.traineddata'],
            charWhitelist: 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789',
            validationRegex: '[A-Z0-9]{8}$',
            minConfidence: 85,
            reportingEnabled : true
          }
        },
        cutoutConfig: {
          style: 'rect',
          maxWidthPercent: '80%',
          maxHeightPercent: '80%',
          alignment: 'center',
          width: 540,
          ratioFromSize: {
            width: 5,
            height: 1
          },
          strokeWidth: 2,
          cornerRadius: 10,
          strokeColor: 'FFFFFF',
          outerColor: '000000',
          outerAlpha: 0.3,
          feedbackStrokeColor: '0099FF'
        },
        scanFeedback: {
          style: 'contour_point',
          strokeWidth: 3,
          strokeColor: '0099FF',
          fillColor: '220099FF',
          beepOnResult: true,
          vibrateOnResult: true,
          blinkAnimationOnResult: true
        },
        doneButton: { // iOS only. Android uses hardware back button.
          title: 'OK',
          type: 'rect', // fullwidth, rect
          cornerRadius: 0,
          textColor: 'FFFFFF',
          textColorHighlighted: 'CCCCCC',
          fontSize: 33,
          fontName: 'HelveticaNeue',
          positionXAlignment: 'center', // left,right,center - no affect on fullwidth
          positionYAlignment: 'bottom', // top, center, bottom
          offset: {
              x: 0, // postive -> right
              y: -88, // postive -> down
          }
        },
        cancelOnResult: true
      }
    };

  constructor() {

  }

  public scan() {
    try {
        cordova.exec(
            this.onSuccess,
            this.onError,
            'AnylineSDK',
            'scan',
            [this.LICENSE_KEY, this.viewConfig]);
    } catch (error) {
        console.log(error);
    }
  }

  private onSuccess(result: any) {
    console.log(result);
  }

  private onError(error: any) {
    console.log(error);
  }
`

**Comment by JonasLaux** [comment]
Hey,
could you please provide the device Log from Logcat?

**Comment by Atee134** [comment]
I found a slightly suspicious entry:
05-15 16:27:07.054 31430 31430 W System.err: java.io.FileNotFoundException: www/assets/anyline_capitals.traineddata: com.devtest

downloading the trained data manually from [https://github.com/Anyline/anyline-ocr-examples-android/blob/master/TrainedModels/anyline_capitals.traineddata](url) and copying it to www/assets solved the issue.

**Comment by JonasLaux** [comment]
Glad to hear!
We will try to improve the error handling from native through Javascript. 
Thanks for sharing your solution.
