### ISSUE TITLE
Is it possible to use anyline in a windowed mode?

### ISSUE THREAD

**Issue by Atee134** [Anyline/anyline-ocr-cordova-module#34]
**I'm submitting a ...**  
[ ] bug report
[ ] feature request
[x] general question

Is it possible, that when I call cordova.exec(....)
The camera with the scanning view is not in full screen, but only part of the screen?

**Comment by PhiMue** [comment]
Hello,

Unfortunately it's not possible to use a customized frame at the moment via the js config.

This change needs to be in the native parts (the Anyline plugin itself). The native parts (iOS, Android, UWP) are open source and you can change them if you want to. Keep in mind that if you update to a newer version of our plugin, you will loose those modifications.

Feel free to issue a pull request, if you find a neat solution.
