### ISSUE TITLE
Failed to install pods

### ISSUE THREAD

**Issue by AareFabrik** [Anyline/anyline-ocr-cordova-module#35]
**Anyline Cordova Plugin version:** 
10.1

**I'm submitting a ...**  
[x] bug report
[ ] feature request
[ ] general question

**Occurring on ...**  
[ ] Android
[x] iOS

**Current behavior:**

When running: 
```cordova platform add ios```
or:
```cordova plugin add io-anyline-cordova```

I get this exception:
```Failed to install 'io-anyline-cordova': Error: pod: Command failed with exit code 31 Error output:
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin18/rbconfig.rb:215: warning: Insecure world writable dir /Users/Rawsix/Library in PATH, mode 040707
    at ChildProcess.whenDone (/Users/Rawsix/Documents/Arbeit/Apps/ies_fiori_native 2/platforms/ios/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at ChildProcess.emit (events.js:193:13)
    at maybeClose (internal/child_process.js:999:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:266:5)
```

And this changes are happening in the Podfile:

```platform :ios, '10.0'```
to
```platform :ios, '8.0'```

**Expected behavior:**

keep:
```platform :ios, '10.0'```
This is also the solution, when I change afterwards the podfile to ```platform :ios, '10.0'``` the pod install succeeds.

**Steps to reproduce:**

```cordova platform add ios```
or:
```cordova plugin add io-anyline-cordova```

Any thought why this happens, any solutions? 

Thanks

**Comment by MaximBelov** [comment]
Anyline v11 for android
Anyline v7 for ios
You can fix it 
Install plugin from my fork
https://github.com/MaximBelov/anyline-ocr-cordova-module
Check
https://github.com/MaximBelov/anyline-ocr-cordova-module/blob/master/plugin.xml

**Comment by JonasLaux** [comment]
Also maybe we should change to the podspec tag instead of the deprecated framework tag
