### ISSUE TITLE
Cordova app crashes immediately on startup

### ISSUE THREAD

**Issue by bdrp** [Anyline/anyline-ocr-cordova-module#36]
**Anyline Cordova Plugin version:** 
10.2.1

**I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] general question

**Occurring on ...**
[x] Android
[ ] iOS

**Current behavior:**
Apps crash at startup and kick me back to home screen.

**Expected behavior:**
The app would start at some state of operation, hopefully.

**Steps to reproduce:**
Run the app:
```sh
cordova run android
```

**Related code:**
```javascript
document.addEventListener('deviceready', () => {

    cordova.exec(onResult, onError, "AnylineSDK", "scan", config);
}, false);

function onResult(result) {
    console.log(result);
}

function onError(error) {
    console.log(error);
}
```
Config is defined according to instructions.

I'm using a Samsung Galaxy S8.

**Comment by marcelmerkx** [comment]
hi bdrp - did you try to run the included Example app & does that have the same behaviour?

**Comment by bdrp** [comment]
It doesn't get that far. It starts, but then I get an alert: "Class not found".

**Comment by marcelmerkx** [comment]
sounds a little bit like the SDK is not in your path. May consider to re-install it:
`cordova plugin remove io-anyline-cordova`
and
`cordova plugin add io-anyline-cordova`

**Comment by bdrp** [comment]
Hm, that worked. The question then I guess is what's different between the tutorial and the example.

Thanks for the help.

**Comment by bdrp** [comment]
OK, found the issue. If the configuration doesn't properly match the license key, the app will crash.
