### ISSUE TITLE
I can't add regular expression for license plate scan

### ISSUE THREAD

**Issue by LarsMelander** [Anyline/anyline-ocr-cordova-module#37]
**Anyline Cordova Plugin version:**
10.2.1

**I'm submitting a ...**
[ ] bug report
[x] feature request
[ ] general question

**Occurring on ...**
[x] Android
[ ] iOS

**Current behavior:**
When scanning a plate with an "O" (capital O), it is recognised as a "0" (zero). Adding a regex doesn't change this behaviour.

**Expected behaviour:**
Other scanning modes apply a regex, supposedly. I'd assume it's the same for license plate scanning.

**Comment by lore-any** [comment]
Hi,

For License Plate there is no possibility at the moment to add a regex. The only plugin where you can do this is OCR. 

Kind regards,
Lorena

**Comment by marcelmerkx** [comment]
@bdrp , if you change from bug to feature request, I'll say +1 😋

@Lorena, fyi, to me it also does make sense to do regex on the plates. Use cases where you are certain up front of certain formats may reduce false positives.

**Comment by bdrp** [comment]
@marcelmerkx Not sure how I do that. Is it enough with a comment update?

**Comment by marcelmerkx** [comment]
I think you did it :) , so: +1 !
