### ISSUE TITLE
Problem with plate recognition

### ISSUE THREAD

**Issue by bdrp** [Anyline/anyline-ocr-cordova-module#38]
**Anyline Cordova Plugin version:** 
10.2.1

**I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] general question

**Occurring on ...**
[x] Android
[ ] iOS

**Current behavior:**
Plate recognition has an error. 3 is interpreted as 5.

**Expected behavior:**
That 3s are identified correctly.

**Steps to reproduce:**
Scan a Swedish car plate with a 3 in it.

**Other information:**
Snapshot: [Dropbox link](https://www.dropbox.com/s/rdos7vr7qxyjhuo/Screenshot_20190625-123743_Register.jpg?dl=0)

**Comment by JonasLaux** [comment]
Hey,
this is not related to our Cordova Plugin. This needs further RnD analysis. Please write to our [support](support@anyline.com) or open up directly a ticket in our [helpdesk](https://9yards.atlassian.net/servicedesk/customer/portals).
