### ISSUE TITLE
conflict with firebasex - android build failed

### ISSUE THREAD

**Issue by RoiDayan1** [Anyline/anyline-ocr-cordova-module#43]
**Anyline Cordova Plugin version:** 

**I'm submitting a ...**  
[x ] bug report
[ ] feature request
[ ] general question

**Occurring on ...**  
[x ] Android
[ ] iOS

**Current behavior:**
android build failed when anyline plugin and firebasex plugin are installed together.

**Expected behavior:**
android build should succeed.

**Steps to reproduce:**

1. create new ionic v3 project
`ionic start NewProject blank --type=ionic-angular`
2. add android platform
`ionic cordova platform add android`
3. add anyline plugin
`ionic cordova plugin add io-anyline-cordova`
4. run build - success
`ionic cordova build android`
5. add firebasex plugin
`ionic cordova plugin add cordova-plugin-firebasex`
6. **run build - failed**
`ionic cordova build android`

**error:**
```
In project 'app' a resolved Google Play services library dependency depends on another at an exact version (e.g. "[17.0.
  2]", but isn't being resolved to that version. Behavior exhibited by the library will be unknown.
  
  Dependency failing: com.google.firebase:firebase-ml-vision-face-model:17.0.2 -> com.google.android.gms:play-services-vis
  ion-common@[17.0.2], but play-services-vision-common version was 18.0.0.
```

any idea how to solve this conflicts?

**Comment by melaniamuir** [comment]
Hello Roi!
Are you still facing this issue? If so, please simply update to Anyline 20 which contains a fix for this error. Thanks!
