### ISSUE TITLE
Not woring 

### ISSUE THREAD

**Issue by iphone201988** [Anyline/anyline-ocr-cordova-module#46]
D/AnylinePlugin: Starting action: scan
W/System.err: org.json.JSONException: Value null at 1 of type org.json.JSONObject$1 cannot be converted to JSONObject
        at org.json.JSON.typeMismatch(JSON.java:101)
        at org.json.JSONArray.getJSONObject(JSONArray.java:527)
        at io.anyline.cordova.AnylinePlugin.scanAnyline4(AnylinePlugin.java:122)
        at io.anyline.cordova.AnylinePlugin.startScanning(AnylinePlugin.java:106)
        at io.anyline.cordova.AnylinePlugin.checkPermission(AnylinePlugin.java:86)
        at io.anyline.cordova.AnylinePlugin.access$400(AnylinePlugin.java:27)
W/System.err:     at io.anyline.cordova.AnylinePlugin$1.run(AnylinePlugin.java:72)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)

[ ] general question

**Occurring on ...**  
[ ] Android
[ ] iOS

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert code snippets here
```

**Other information:**

**Comment by JonasLaux** [comment]
Thanks for reaching in the question. Unfortunately we need more information. Which phone did you use. Is it you application or the demo app? How did you implement it? Which steps are needed to reproduce it?
Without any more information i have to close this issue for now. If you can provide the answers from the template, feel free to open it again.

**Comment by iphone201988** [comment]
1) Which phone did you use?
I am using Mi Poco F1 phone. 

2) Is it you application or the demo app?
It is my application.

3) How did you implement it?
 I am ionic platform and Anyline plugin. 

4)  Which steps are needed to reproduce it.
The issue when call the .scan().

**Comment by JonasLaux** [comment]
Could you provide the code how you implemented it?
Is it on every ScanMode?

**Comment by iphone201988** [comment]
licenseKey: "XXXSOMTHINGXXXXXXX";
  anylineLicensePlateViewConfig: {
    "camera" : {
        "captureResolution" : "1080p",
        "zoomGesture" : true 
    },
    "flash" : {
        "mode" : "manual",
        "alignment" : "top_left"
    },
    "viewPlugin" : {
        "plugin" : {
            "id" : "LicensePlate_ID",
            "licensePlatePlugin" : {
            }
        },
        "cutoutConfig" : {
            "style": "rect",
            "maxWidthPercent": "80%",
            "maxHeightPercent": "80%",
            "alignment": "top_half",
            "width": 720,
            "ratioFromSize": {
                "width": 2,
                "height": 1
            },
            "strokeWidth": 2,
            "cornerRadius": 10,
            "strokeColor": "FFFFFF",
            "outerColor": "000000",
            "outerAlpha": 0.3,
            "feedbackStrokeColor": "0099FF"
        },
        "scanFeedback" : {
            "animationDuration": 0,
            "style": "RECT",
            "strokeWidth": 2,
            "strokeColor": "0099FF",
            "blinkOnResult": true,
            "beepOnResult": true,
            "vibrateOnResult": true
        },
        "cancelOnResult" : true,
        "delayStartScanTime":2000
    }
};
__________________________________

    const options1: AnylineOptions = {
          licenseKey: this.licenseKey,
          config: this.anylineLicensePlateViewConfig
        }

    this.anyline.scan(options1)
  .then((res: any) => console.log(res))
  .catch((error: any) => console.error(error));

**Comment by JonasLaux** [comment]
Unfortunately we haven't implemented Promises yet. Our Cordova Plugin uses callbacks.
This is the line from our example app to implement the call:
https://github.com/Anyline/anyline-ocr-cordova-module/blob/master/example/www/js/anyline.licensePlate.js#L111

**Comment by iphone201988** [comment]
Let me try this. Please provide proper code on https://ionicframework.com/docs/native/anyline implementation it is really very hard.

**Comment by JonasLaux** [comment]
Ok, you're right, we haven't paid attention on this ionic documentation. Thanks for mentioning it.
If you need more information, here is our documentation:
https://documentation.anyline.com/toc/platforms/cordova/getting_started.html
