### ISSUE TITLE
[Barcode scanning] The plugin crashes on startup

### ISSUE THREAD

**Issue by eidanfi** [Anyline/anyline-ocr-cordova-module#56]
When i trigger the function that open the camera, the app immediately crash.
(<any>window).cordova.exec(onResult, onError, "AnylineSDK", "scan", [ANYLINE_LICENSE_KEY, ANYLINE_MRZ_CONFIG]);

Environment: ionic 3 with cordova 10
Anyline version: 34

anyline config: {
  'camera': {
    'captureResolution': '1080p'
  },
  'flash': {
    'mode': 'auto',
    'alignment': 'bottom_right'
  },
  'viewPlugin': {
    'plugin': {
      'id': 'Barcode_ID',
      'barcodePlugin': {}
    },
    'cutoutConfig': {
      'style': 'rect',
      'maxWidthPercent': '80%',
      'maxHeightPercent': '80%',
      'alignment': 'center',
      'ratioFromSize': {
        'width': 100,
        'height': 80
      },
      'strokeWidth': 1,
      'cornerRadius': 3,
      'strokeColor': 'FFFFFF',
      'outerColor': '000000',
      'outerAlpha': 0.3,
      'feedbackStrokeColor': '0099FF'
    },
    'scanFeedback': {
      'style': 'rect',
      'strokeColor': '0099FF',
      'fillColor': '220099FF',
      'animationDuration': 150,
      'blinkOnResult': true,
      'beepOnResult': true,
      'vibrateOnResult': true
    },
    'cancelOnResult': true
  }
}

**Comment by berndkamplanyline** [comment]
We don't actively monitor the Github Issues, please raise a support request using the Anyline Helpdesk. Link to Anyline Helpdesk: https://anyline.atlassian.net/servicedesk/customer/portal/2/group/6

When raising a support request based on this Github Issue, please fill out and include the following information:

---
Support request concerning Anyline Github Repository: [URL to relevant Anyline Github Repository here]
Support request based on Github Issue: [URL to relevant Github Issue here]

---

Thank you so much!
