### ISSUE TITLE
Comma detection issue

### ISSUE THREAD

**Issue by pashkevich-d** [Anyline/anyline-ocr-cordova-module#59]
Hi, we are using Ionic 5 and io-anyline-cordova plugin version 25, and many our users are complaining about comma detection. For example instead of 16455 the camera catches 164551. Is there any chance that after updating plugin to the latest version this issue will be fixed, or we can change something in anyline config to improve the quality of comma recognition?

This is our current anyline config:

```
{
		camera: {
			captureResolution: '720',
			pictureResolution: '1080',
			zoomGesture: true,
		},
		flash: {
			mode: 'auto',
			alignment: 'bottom_right',
		},
		viewPlugin: {
			plugin: {
				id: 'Meter_ID',
				meterPlugin: {
					scanMode: 'AUTO_ANALOG_DIGITAL_METER',
				},
			},
			cutoutConfig: {
				style: 'rect',
				maxWidthPercent: '80%',
				maxHeightPercent: '80%',
				alignment: 'center',
				width: 540,
				ratioFromSize: {
					width: 5,
					height: 1,
				},
				offset: {
					x: 0,
					y: 0,
				},
				cropPadding: {
					x: 0,
					y: 0,
				},
				cropOffset: {
					x: 0,
					y: 0,
				},
				strokeWidth: 2,
				cornerRadius: 10,
				strokeColor: 'FFFFFF',
				outerColor: '000000',
				outerAlpha: 0.3,
				feedbackStrokeColor: '0099FF',
			},
			scanFeedback: {
				style: 'contour_point',
				strokeWidth: 2,
				strokeColor: '0099FF',
				fillColor: '220099FF',
				beepOnResult: true,
				vibrateOnResult: true,
				blinkAnimationOnResult: true,
			},
			cancelOnResult: true,
			delayStartScanTime: 2000,
		},
		doneButton: {
			title: 'Abbrechen',
		},
	}
```

**Comment by berndkamplanyline** [comment]
We don't actively monitor the Github Issues, please raise a support request using the Anyline Helpdesk. Link to Anyline Helpdesk: https://anyline.atlassian.net/servicedesk/customer/portal/2/group/6

When raising a support request based on this Github Issue, please fill out and include the following information:

---
Support request concerning Anyline Github Repository: [URL to relevant Anyline Github Repository here]
Support request based on Github Issue: [URL to relevant Github Issue here]

---

Thank you so much!
