### ISSUE TITLE
Multiple APK support

### ISSUE THREAD

**Issue by joaoppedrosa** [Anyline/anyline-ocr-cordova-module#6]
Hi, 

I'm trying to deploy a version with multiple apk (x86 and armv7) and I would like to know if the anyline plugin support this feature. Because now when i'm trying to build the splited apk, it includes both architectures.

**Comment by JonasLaux** [comment]
Hi,
what exactly are you trying to build. Your Cordova App with our Plugin? Did you tried this guide?
https://developer.android.com/studio/build/configure-apk-splits.html

**Comment by joaoppedrosa** [comment]
I have a project with splited ABIs, and when I assemble a debug or release apk it work fine. 
But after I include Anyline to the project, everytime that I assemble a apk, they come splited but inside of the apk contains both of the ABIs (armv7 and x86).

**Comment by JonasLaux** [comment]
Hi, 
sorry for the late response, if you want to have split ABIs you can easily add
`splits {
        abi {
            enable true
            reset()
            include 'x86', 'armeabi-v7a'
            universalApk false
        }
  }`

in the build gradle under android.
