### ISSUE TITLE
ActivityNotFoundException

### ISSUE THREAD

**Issue by Oninjutsu** [Anyline/anyline-ocr-cordova-module#77]
**Anyline Cordova Plugin version:** 

**I'm submitting a ...**  
[x] bug report
[ ] feature request
[ ] general question

**Occurring on ...**  
[x] Android
[ ] iOS

**Current behavior:**
The plugin.xml contains declaration of ScanActivity.java in the AndroidManifest.xml but there is a raised exception:

ActivityNotFoundException.Unable to find explicit activity class {<app id>/io.anyline.cordova.ScanActivity}; have you declared this activity in your AndroidManifest.xml?

**Expected behavior:**
No issue
![image](https://user-images.githubusercontent.com/65342582/228100820-901219e9-8641-4c3c-9a91-3036e204c399.png)

**Comment by berndkamplanyline** [comment]
We don't actively monitor the Github Issues, please raise a support request using the Anyline Helpdesk. Link to Anyline Helpdesk: https://anyline.atlassian.net/servicedesk/customer/portal/2/group/6

When raising a support request based on this Github Issue, please fill out and include the following information:

---
Support request concerning Anyline Github Repository: [URL to relevant Anyline Github Repository here]
Support request based on Github Issue: [URL to relevant Github Issue here]

---

Thank you so much!
