### ISSUE TITLE
Using own .traineddata files on iOS

### ISSUE THREAD

**Issue by Darkoon** [Anyline/anyline-ocr-cordova-module#9]
Hello

I'm developing ionic2 app and I encountered problem with plugin on iOS platform. Trying to use my own .traineddata file I expierienced problems with locating it in application. I got my file in `assets` dir and in `io-anyline-cordova/src/ios/anyline_sdk/AnylineResources.bundle/module_anyline_ocr/tessdata`. My ocr config: 
```typescript
ocrConfig: Object = {
    "scanMode": "LINE",
    "traineddataFiles": ["assets/ocrb.traineddata"],
    "charWhitelist": "ĘÓĄŚŁŻŹĆŃABCDEFGHIJKLMNOPQRSTUVWXYZqwertyuiopasdfghjklzxcvuęóąśłżźćń0123456789-.",
    "validationRegex": "[A-Z0-9ĘÓŁŚĄŻŹĆŃ]{17}$",
    "minConfidence": 75,
    "removeSmallContours": true,
    "charPaddingXFactor": 0.5,
    "isBrightTextOnDark": false
  };
```

When debugging in xcode, there is an error:
```
Error opening data file /var/mobile/Containers/Data/Application/<UUID>/Documents/AnylineResources.bundle/module_anyline_ocr/tessdata/ocrb.traineddata

Please make sure the TESSDATA_PREFIX environment variable is set to the parent directory of your "tessdata" directory
```

Where should I place my .traineddata file to use in plugin? I managed to use eng_no_dict.traineddata file that was precopied to AnyLineResources.bundle and it worked without technical problems.

**Comment by JonasLaux** [comment]
Hi,
sorry for the late response.
Place them in your www/assets folder
